// AUTO-GENERATED by scripts/probe/gen-registry.mjs — do not edit by hand.
// Regenerate with:  node scripts/probe/gen-registry.mjs .probe/console-js
//
// Source of truth harvested from the Technitium DNS Server v15.4 web console.
// Every entry doubles as (1) the proxy path allowlist, (2) the HTTP method
// table, (3) the auth/envelope/response-kind policy, and (4) the SDK's
// EndpointId literal union.
//
// Endpoint count: 129

export const API_DOMAINS = [
  'system',
  'user',
  'admin',
  'dashboard',
  'zones',
  'records',
  'dnssec',
  'cache',
  'allowed',
  'blocked',
  'apps',
  'dhcp',
  'logs',
  'settings',
  'dnsClient',
] as const

export type ApiDomain = (typeof API_DOMAINS)[number]

export type ApiMethod = 'GET' | 'POST'

/** How Technitium wraps a successful payload for this endpoint. */
export type ApiEnvelope = 'wrapped' | 'flat'

/** What the proxy does with the upstream body. */
export type ApiKind = 'json' | 'file' | 'upload'

export interface EndpointDef {
  /** HTTP verbs the upstream endpoint accepts; the proxy rejects anything else. */
  readonly methods: readonly ApiMethod[]
  readonly auth: 'none' | 'token'
  readonly envelope: ApiEnvelope
  readonly kind: ApiKind
  readonly domain: ApiDomain
}

export const ENDPOINTS = {
  // ---- system ----
  'status': { methods: ['GET'], auth: 'none', envelope: 'flat', kind: 'json', domain: 'system' },
  // ---- user ----
  'user/2fa/disable': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'user' },
  'user/2fa/enable': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'user' },
  'user/2fa/init': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'user' },
  'user/changePassword': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'user' },
  'user/checkForUpdate': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'user' },
  'user/createSingleUseToken': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'user' },
  'user/createToken': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'user' },
  'user/login': { methods: ['POST'], auth: 'none', envelope: 'flat', kind: 'json', domain: 'user' },
  'user/logout': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'user' },
  'user/profile/get': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'user' },
  'user/profile/set': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'user' },
  'user/session/delete': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'user' },
  'user/session/get': { methods: ['GET'], auth: 'token', envelope: 'flat', kind: 'json', domain: 'user' },
  // ---- admin ----
  'admin/cluster/init': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/cluster/initJoin': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/cluster/primary/delete': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/cluster/primary/deleteSecondary': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/cluster/primary/removeSecondary': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/cluster/primary/setOptions': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/cluster/secondary/leave': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/cluster/secondary/promote': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/cluster/secondary/resync': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/cluster/secondary/updatePrimary': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/cluster/state': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/cluster/updateIpAddress': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/groups/create': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/groups/delete': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/groups/get': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/groups/list': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/groups/set': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/permissions/get': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/permissions/list': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/permissions/set': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/sessions/createToken': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/sessions/delete': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/sessions/list': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/sso/get': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/sso/set': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/users/create': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/users/delete': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/users/get': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/users/list': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  'admin/users/set': { methods: ['GET', 'POST'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'admin' },
  // ---- dashboard ----
  'dashboard/stats/deleteAll': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dashboard' },
  'dashboard/stats/get': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dashboard' },
  'dashboard/stats/getTop': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dashboard' },
  // ---- zones ----
  'zones/catalogs/list': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'zones' },
  'zones/clone': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'zones' },
  'zones/convert': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'zones' },
  'zones/create': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'upload', domain: 'zones' },
  'zones/delete': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'zones' },
  'zones/disable': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'zones' },
  'zones/enable': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'zones' },
  'zones/export': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'file', domain: 'zones' },
  'zones/import': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'upload', domain: 'zones' },
  'zones/list': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'zones' },
  'zones/options/get': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'zones' },
  'zones/options/set': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'zones' },
  'zones/permissions/get': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'zones' },
  'zones/permissions/set': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'zones' },
  'zones/resync': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'zones' },
  // ---- records ----
  'zones/records/add': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'records' },
  'zones/records/delete': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'records' },
  'zones/records/get': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'records' },
  'zones/records/update': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'records' },
  // ---- dnssec ----
  'zones/dnssec/properties/activateKskDnsKey': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/properties/addPrivateKey': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/properties/convertToNSEC': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/properties/convertToNSEC3': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/properties/deletePrivateKey': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/properties/get': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/properties/publishAllPrivateKeys': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/properties/retireDnsKey': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/properties/rolloverDnsKey': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/properties/updateDnsKeyTtl': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/properties/updateNSEC3Params': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/properties/updatePrivateKey': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/sign': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/unsign': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  'zones/dnssec/viewDS': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnssec' },
  // ---- cache ----
  'cache/delete': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'cache' },
  'cache/flush': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'cache' },
  'cache/list': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'cache' },
  // ---- allowed ----
  'allowed/add': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'allowed' },
  'allowed/delete': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'allowed' },
  'allowed/export': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'file', domain: 'allowed' },
  'allowed/flush': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'allowed' },
  'allowed/import': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'upload', domain: 'allowed' },
  'allowed/list': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'allowed' },
  // ---- blocked ----
  'blocked/add': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'blocked' },
  'blocked/delete': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'blocked' },
  'blocked/export': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'file', domain: 'blocked' },
  'blocked/flush': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'blocked' },
  'blocked/import': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'upload', domain: 'blocked' },
  'blocked/list': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'blocked' },
  // ---- apps ----
  'apps/config/get': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'apps' },
  'apps/config/set': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'apps' },
  'apps/downloadAndInstall': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'apps' },
  'apps/downloadAndUpdate': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'apps' },
  'apps/install': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'upload', domain: 'apps' },
  'apps/list': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'apps' },
  'apps/listStoreApps': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'apps' },
  'apps/uninstall': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'apps' },
  'apps/update': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'upload', domain: 'apps' },
  // ---- dhcp ----
  'dhcp/leases/convertToDynamic': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dhcp' },
  'dhcp/leases/convertToReserved': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dhcp' },
  'dhcp/leases/list': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dhcp' },
  'dhcp/leases/remove': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dhcp' },
  'dhcp/scopes/delete': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dhcp' },
  'dhcp/scopes/disable': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dhcp' },
  'dhcp/scopes/enable': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dhcp' },
  'dhcp/scopes/get': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dhcp' },
  'dhcp/scopes/list': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dhcp' },
  'dhcp/scopes/set': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dhcp' },
  // ---- logs ----
  'logs/delete': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'logs' },
  'logs/deleteAll': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'logs' },
  'logs/download': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'file', domain: 'logs' },
  'logs/export': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'file', domain: 'logs' },
  'logs/list': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'logs' },
  'logs/query': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'logs' },
  // ---- settings ----
  'settings/backup': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'file', domain: 'settings' },
  'settings/forceUpdateBlockLists': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'settings' },
  'settings/get': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'settings' },
  'settings/getTsigKeyNames': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'settings' },
  'settings/restore': { methods: ['POST'], auth: 'token', envelope: 'wrapped', kind: 'upload', domain: 'settings' },
  'settings/set': { methods: ['POST', 'GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'settings' },
  'settings/temporaryDisableBlocking': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'settings' },
  // ---- dnsClient ----
  'dnsClient/resolve': { methods: ['GET'], auth: 'token', envelope: 'wrapped', kind: 'json', domain: 'dnsClient' },
} as const satisfies Record<string, EndpointDef>

export type EndpointId = keyof typeof ENDPOINTS

/** Narrow an endpoint id to a single domain — used to type the SDK modules. */
export type EndpointIdOf<D extends ApiDomain> = {
  [K in EndpointId]: (typeof ENDPOINTS)[K]['domain'] extends D ? K : never
}[EndpointId]

export const ENDPOINT_COUNT = 129 as const

/** Runtime guard used by the proxy to reject anything outside the allowlist. */
export function isKnownEndpoint(path: string): path is EndpointId {
  return Object.hasOwn(ENDPOINTS, path)
}

export function getEndpoint(path: string): EndpointDef | undefined {
  return isKnownEndpoint(path) ? ENDPOINTS[path] : undefined
}
